CREATE DATABASE Loja;

USE Loja;

CREATE TABLE FUNCIONARIO(
	CODIGO INT PRIMARY KEY,
	NOME VARCHAR (30) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL,
	CONFIRMA_EMAIL VARCHAR (50) NOT NULL,
	PERMISSAO CHAR(10) NOT NULL,
	SENHA VARCHAR (50) NOT NULL,
	CONFIRMA_SENHA VARCHAR(50) NOT NULL
);

