CREATE DATABASE Loja;

USE Loja;

CREATE TABLE FUNCIONARIO(
	CODIGO INT PRIMARY KEY,
	NOME VARCHAR (30) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL,
	CONFIRMA_EMAIL VARCHAR (50) NOT NULL,
	PERMISSAO CHAR(10) NOT NULL,
	SENHA VARCHAR (50) NOT NULL,
	CONFIRMA_SENHA VARCHAR(50) NOT NULL
);

CREATE TABLE MARCA(
	CODIGO_MARCA INT PRIMARY KEY,
	NOME_MARCA VARCHAR (30) NOT NULL
);

CREATE TABLE CATEGORIA(
	CODIGO_CATEGORIA INT PRIMARY KEY,
	NOME_CATEGORIA VARCHAR (30) NOT NULL
);

CREATE TABLE TAMANHO(
	CODIGO_TAMANHO INT PRIMARY KEY,
	NOME_TAMANHO CHAR (6) NOT NULL
);
