CREATE DATABASE Loja;

USE Loja;

CREATE TABLE FUNCIONARIO(
	CODIGO INT PRIMARY KEY,
	NOME VARCHAR (30) NOT NULL,
	EMAIL VARCHAR (50) NOT NULL,
	CONFIRMA_EMAIL VARCHAR (50) NOT NULL,
	PERMISSAO CHAR(10) NOT NULL,
	SENHA VARCHAR (50) NOT NULL,
	CONFIRMA_SENHA VARCHAR(50) NOT NULL
);

CREATE TABLE MARCA(
	CODIGO_MARCA INT PRIMARY KEY,
	NOME_MARCA VARCHAR (30) NOT NULL
);

CREATE TABLE CATEGORIA(
	CODIGO_CATEGORIA INT PRIMARY KEY,
	NOME_CATEGORIA VARCHAR (30) NOT NULL
);

CREATE TABLE TAMANHO(
	CODIGO_TAMANHO INT PRIMARY KEY,
	NOME_TAMANHO CHAR (6) NOT NULL
);

CREATE TABLE PRODUTO(
    CODIGO_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR (30) NOT NULL,
    COR CHAR (15) NOT NULL,
    CODIGO_MARCA INT, FOREIGN KEY (CODIGO_MARCA) REFERENCES MARCA(CODIGO_MARCA),
    CODIGO_CATEGORIA INT, FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO_CATEGORIA),
    CODIGO_TAMANHO INT, FOREIGN KEY (CODIGO_TAMANHO) REFERENCES TAMANHO(CODIGO_TAMANHO),
    PRECO REAL NOT NULL,
    QUANTIDADE INT NOT NULL,
    DESCRICAO VARCHAR (100) NOT NULL
);

INSERT INTO FUNCIONARIO VALUES(
        1 , 'COMUM' , 'COMUN@COMUUM.COM' , 'COMUN@COMUUM.COM' , 'COMUM' , 'COMUM1234' , 'COMUM1234'
                              );

INSERT INTO MARCA VALUES(
        1 , 'NIKE'
                        );

INSERT INTO MARCA VALUES(
        2 , 'ADIDAS'
                        );

INSERT INTO MARCA VALUES(
        3 , 'PUMA'
                        );

INSERT INTO CATEGORIA VALUES(
        1 , 'CAMISA'
                            );

INSERT INTO CATEGORIA VALUES(
       2 , 'BLUSA'
                            );

INSERT INTO CATEGORIA VALUES(
       3 , 'CALCA'
                            );

INSERT INTO TAMANHO VALUES(
       1 , 'P'
                          );

INSERT INTO TAMANHO VALUES(
       2 , 'M'
                          );

INSERT INTO TAMANHO VALUES(
       3 , 'G'
                          );


INSERT INTO PRODUTO VALUES(
       1 , 'CAMISETA NIKE SB UNISSEX' , 'PRETO' , 1 , 1 , 1 , 120.00 , 50 , 'O tecido jersey macio no contato com a pele.'
                          );

INSERT INTO PRODUTO VALUES(
       2 , 'BLUSA CAPUZ TREFOIL' , 'BRANCO' , 2 , 2 , 2 , 310.00 , 25 , 'Equilibrada, modelagem nem justa nem folgada demais.'
                          );

INSERT INTO PRODUTO VALUES(
       3 , 'PUMA X PEANUTS CALCA MOLETOM' , 'CINZA' , 3 , 3 , 3 , 499.90 , 80 , ' Feita em material de algodao sustentavel.'
                          );
